/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.records;


import java.time.Duration;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.ng200.openolympus.jooq.tables.TimeExtension;
import org.ng200.openolympus.jooq.tables.interfaces.ITimeExtension;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "time_extension", schema = "public")
public class TimeExtensionRecord extends UpdatableRecordImpl<TimeExtensionRecord> implements Record5<Long, Duration, String, Long, Integer>, ITimeExtension {

	private static final long serialVersionUID = -2023569567;

	/**
	 * Setter for <code>public.time_extension.id</code>.
	 */
	@Override
	public TimeExtensionRecord setId(Long value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.time_extension.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 64)
	@Override
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>public.time_extension.duration</code>.
	 */
	@Override
	public TimeExtensionRecord setDuration(Duration value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.time_extension.duration</code>.
	 */
	@Column(name = "duration", precision = 64)
	@Override
	public Duration getDuration() {
		return (Duration) getValue(1);
	}

	/**
	 * Setter for <code>public.time_extension.reason</code>.
	 */
	@Override
	public TimeExtensionRecord setReason(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.time_extension.reason</code>.
	 */
	@Column(name = "reason")
	@Override
	public String getReason() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.time_extension.user_id</code>.
	 */
	@Override
	public TimeExtensionRecord setUserId(Long value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.time_extension.user_id</code>.
	 */
	@Column(name = "user_id", nullable = false, precision = 64)
	@Override
	public Long getUserId() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>public.time_extension.contest_id</code>.
	 */
	@Override
	public TimeExtensionRecord setContestId(Integer value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.time_extension.contest_id</code>.
	 */
	@Column(name = "contest_id", nullable = false, precision = 32)
	@Override
	public Integer getContestId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Duration, String, Long, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Duration, String, Long, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TimeExtension.TIME_EXTENSION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Duration> field2() {
		return TimeExtension.TIME_EXTENSION.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TimeExtension.TIME_EXTENSION.REASON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return TimeExtension.TIME_EXTENSION.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return TimeExtension.TIME_EXTENSION.CONTEST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Duration value2() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getReason();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getContestId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionRecord value2(Duration value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionRecord value3(String value) {
		setReason(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionRecord value4(Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionRecord value5(Integer value) {
		setContestId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionRecord values(Long value1, Duration value2, String value3, Long value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ITimeExtension from) {
		setId(from.getId());
		setDuration(from.getDuration());
		setReason(from.getReason());
		setUserId(from.getUserId());
		setContestId(from.getContestId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ITimeExtension> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TimeExtensionRecord
	 */
	public TimeExtensionRecord() {
		super(TimeExtension.TIME_EXTENSION);
	}

	/**
	 * Create a detached, initialised TimeExtensionRecord
	 */
	public TimeExtensionRecord(Long id, Duration duration, String reason, Long userId, Integer contestId) {
		super(TimeExtension.TIME_EXTENSION);

		setValue(0, id);
		setValue(1, duration);
		setValue(2, reason);
		setValue(3, userId);
		setValue(4, contestId);
	}
}
