/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.records;

import java.math.BigDecimal;
import java.time.Duration;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.ng200.openolympus.jooq.enums.VerdictStatusType;
import org.ng200.openolympus.jooq.tables.Verdict;
import org.ng200.openolympus.jooq.tables.interfaces.IVerdict;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
						"http://www.jooq.org",
						"jOOQ version:3.6.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
					"all",
					"unchecked",
					"rawtypes"
})
@Entity
@Table(name = "verdict", schema = "public")
public class VerdictRecord extends UpdatableRecordImpl<VerdictRecord>implements
		Record11<Long, BigDecimal, BigDecimal, VerdictStatusType, Boolean, String, Duration, Duration, Long, String, Long>,
		IVerdict {

	private static final long serialVersionUID = 1934849345;

	/**
	 * Create a detached VerdictRecord
	 */
	public VerdictRecord() {
		super(Verdict.VERDICT);
	}

	/**
	 * Create a detached, initialised VerdictRecord
	 */
	public VerdictRecord(Long id, BigDecimal score, BigDecimal maximumScore,
			VerdictStatusType status, Boolean viewableDuringContest,
			String path, Duration cpuTime, Duration realTime, Long memoryPeak,
			String additionalInformation, Long solutionId) {
		super(Verdict.VERDICT);

		this.setValue(0, id);
		this.setValue(1, score);
		this.setValue(2, maximumScore);
		this.setValue(3, status);
		this.setValue(4, viewableDuringContest);
		this.setValue(5, path);
		this.setValue(6, cpuTime);
		this.setValue(7, realTime);
		this.setValue(8, memoryPeak);
		this.setValue(9, additionalInformation);
		this.setValue(10, solutionId);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Verdict.VERDICT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Verdict.VERDICT.ADDITIONAL_INFORMATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field11() {
		return Verdict.VERDICT.SOLUTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return Verdict.VERDICT.SCORE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return Verdict.VERDICT.MAXIMUM_SCORE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<VerdictStatusType> field4() {
		return Verdict.VERDICT.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field5() {
		return Verdict.VERDICT.VIEWABLE_DURING_CONTEST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Verdict.VERDICT.PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Duration> field7() {
		return Verdict.VERDICT.CPU_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Duration> field8() {
		return Verdict.VERDICT.REAL_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field9() {
		return Verdict.VERDICT.MEMORY_PEAK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Long, BigDecimal, BigDecimal, VerdictStatusType, Boolean, String, Duration, Duration, Long, String, Long> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IVerdict from) {
		this.setId(from.getId());
		this.setScore(from.getScore());
		this.setMaximumScore(from.getMaximumScore());
		this.setStatus(from.getStatus());
		this.setViewableDuringContest(from.getViewableDuringContest());
		this.setPath(from.getPath());
		this.setCpuTime(from.getCpuTime());
		this.setRealTime(from.getRealTime());
		this.setMemoryPeak(from.getMemoryPeak());
		this.setAdditionalInformation(from.getAdditionalInformation());
		this.setSolutionId(from.getSolutionId());
	}

	/**
	 * Getter for <code>public.verdict.additional_information</code>.
	 */
	@Column(name = "additional_information")
	@Override
	public String getAdditionalInformation() {
		return (String) this.getValue(9);
	}

	/**
	 * Getter for <code>public.verdict.cpu_time</code>.
	 */
	@Column(name = "cpu_time", precision = 64)
	@Override
	public Duration getCpuTime() {
		return (Duration) this.getValue(6);
	}

	/**
	 * Getter for <code>public.verdict.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 64)
	@Override
	public Long getId() {
		return (Long) this.getValue(0);
	}

	/**
	 * Getter for <code>public.verdict.maximum_score</code>.
	 */
	@Column(name = "maximum_score", nullable = false, precision = 19, scale = 2)
	@Override
	public BigDecimal getMaximumScore() {
		return (BigDecimal) this.getValue(2);
	}

	/**
	 * Getter for <code>public.verdict.memory_peak</code>.
	 */
	@Column(name = "memory_peak", precision = 64)
	@Override
	public Long getMemoryPeak() {
		return (Long) this.getValue(8);
	}

	/**
	 * Getter for <code>public.verdict.path</code>.
	 */
	@Column(name = "path", nullable = false)
	@Override
	public String getPath() {
		return (String) this.getValue(5);
	}

	/**
	 * Getter for <code>public.verdict.real_time</code>.
	 */
	@Column(name = "real_time", precision = 64)
	@Override
	public Duration getRealTime() {
		return (Duration) this.getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.verdict.score</code>.
	 */
	@Column(name = "score", precision = 19, scale = 2)
	@Override
	public BigDecimal getScore() {
		return (BigDecimal) this.getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.verdict.solution_id</code>.
	 */
	@Column(name = "solution_id", precision = 64)
	@Override
	public Long getSolutionId() {
		return (Long) this.getValue(10);
	}

	/**
	 * Getter for <code>public.verdict.status</code>.
	 */
	@Column(name = "status", nullable = false)
	@Override
	public VerdictStatusType getStatus() {
		return (VerdictStatusType) this.getValue(3);
	}

	/**
	 * Getter for <code>public.verdict.viewable_during_contest</code>.
	 */
	@Column(name = "viewable_during_contest", nullable = false)
	@Override
	public Boolean getViewableDuringContest() {
		return (Boolean) this.getValue(4);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IVerdict> E into(E into) {
		into.from(this);
		return into;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	/**
	 * Setter for <code>public.verdict.additional_information</code>.
	 */
	@Override
	public VerdictRecord setAdditionalInformation(String value) {
		this.setValue(9, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.cpu_time</code>.
	 */
	@Override
	public VerdictRecord setCpuTime(Duration value) {
		this.setValue(6, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.id</code>.
	 */
	@Override
	public VerdictRecord setId(Long value) {
		this.setValue(0, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.maximum_score</code>.
	 */
	@Override
	public VerdictRecord setMaximumScore(BigDecimal value) {
		this.setValue(2, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.memory_peak</code>.
	 */
	@Override
	public VerdictRecord setMemoryPeak(Long value) {
		this.setValue(8, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.path</code>.
	 */
	@Override
	public VerdictRecord setPath(String value) {
		this.setValue(5, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.real_time</code>.
	 */
	@Override
	public VerdictRecord setRealTime(Duration value) {
		this.setValue(7, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.score</code>.
	 */
	@Override
	public VerdictRecord setScore(BigDecimal value) {
		this.setValue(1, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.solution_id</code>.
	 */
	@Override
	public VerdictRecord setSolutionId(Long value) {
		this.setValue(10, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.status</code>.
	 */
	@Override
	public VerdictRecord setStatus(VerdictStatusType value) {
		this.setValue(3, value);
		return this;
	}

	/**
	 * Setter for <code>public.verdict.viewable_during_contest</code>.
	 */
	@Override
	public VerdictRecord setViewableDuringContest(Boolean value) {
		this.setValue(4, value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return this.getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value1(Long value) {
		this.setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return this.getAdditionalInformation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value10(String value) {
		this.setAdditionalInformation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value11() {
		return this.getSolutionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value11(Long value) {
		this.setSolutionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return this.getScore();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value2(BigDecimal value) {
		this.setScore(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return this.getMaximumScore();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value3(BigDecimal value) {
		this.setMaximumScore(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictStatusType value4() {
		return this.getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value4(VerdictStatusType value) {
		this.setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value5() {
		return this.getViewableDuringContest();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value5(Boolean value) {
		this.setViewableDuringContest(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return this.getPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value6(String value) {
		this.setPath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Duration value7() {
		return this.getCpuTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value7(Duration value) {
		this.setCpuTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Duration value8() {
		return this.getRealTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value8(Duration value) {
		this.setRealTime(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value9() {
		return this.getMemoryPeak();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord value9(Long value) {
		this.setMemoryPeak(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerdictRecord values(Long value1, BigDecimal value2,
			BigDecimal value3, VerdictStatusType value4, Boolean value5,
			String value6, Duration value7, Duration value8, Long value9,
			String value10, Long value11) {
		this.value1(value1);
		this.value2(value2);
		this.value3(value3);
		this.value4(value4);
		this.value5(value5);
		this.value6(value6);
		this.value7(value7);
		this.value8(value8);
		this.value9(value9);
		this.value10(value10);
		this.value11(value11);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Long, BigDecimal, BigDecimal, VerdictStatusType, Boolean, String, Duration, Duration, Long, String, Long> valuesRow() {
		return (Row11) super.valuesRow();
	}
}
