/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContestQuestions extends org.jooq.impl.TableImpl<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord> {

	private static final long serialVersionUID = 1542330966;

	/**
	 * The reference instance of <code>public.contest_questions</code>
	 */
	public static final org.ng200.openolympus.jooq.tables.ContestQuestions CONTEST_QUESTIONS = new org.ng200.openolympus.jooq.tables.ContestQuestions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord> getRecordType() {
		return org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord.class;
	}

	/**
	 * The column <code>public.contest_questions.id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.contest_questions.created_date</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, java.sql.Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.contest_questions.last_modified_date</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, java.sql.Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.contest_questions.question</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, java.lang.String> QUESTION = createField("question", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.contest_questions.response</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, java.lang.String> RESPONSE = createField("response", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.contest_questions.contest_id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, java.lang.Long> CONTEST_ID = createField("contest_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.contest_questions.created_by_id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, java.lang.Long> CREATED_BY_ID = createField("created_by_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.contest_questions.last_modified_by_id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, java.lang.Long> LAST_MODIFIED_BY_ID = createField("last_modified_by_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.contest_questions.user_id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.contest_questions</code> table reference
	 */
	public ContestQuestions() {
		this("contest_questions", null);
	}

	/**
	 * Create an aliased <code>public.contest_questions</code> table reference
	 */
	public ContestQuestions(java.lang.String alias) {
		this(alias, org.ng200.openolympus.jooq.tables.ContestQuestions.CONTEST_QUESTIONS);
	}

	private ContestQuestions(java.lang.String alias, org.jooq.Table<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private ContestQuestions(java.lang.String alias, org.jooq.Table<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ng200.openolympus.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord> getPrimaryKey() {
		return org.ng200.openolympus.jooq.Keys.CONTEST_QUESTIONS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord>>asList(org.ng200.openolympus.jooq.Keys.CONTEST_QUESTIONS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord, ?>>asList(org.ng200.openolympus.jooq.Keys.CONTEST_QUESTIONS__FK_6FQYKIQBJNVDU7QFUOSV95IKW, org.ng200.openolympus.jooq.Keys.CONTEST_QUESTIONS__FK_NNNILJ5LPLC8GY15SEGSB5VUI, org.ng200.openolympus.jooq.Keys.CONTEST_QUESTIONS__FK_DO6VS8XP449PK0001124M05R6, org.ng200.openolympus.jooq.Keys.CONTEST_QUESTIONS__FK_PY8FJ36W1K14S310T0YRC72D0);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ng200.openolympus.jooq.tables.ContestQuestions as(java.lang.String alias) {
		return new org.ng200.openolympus.jooq.tables.ContestQuestions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ng200.openolympus.jooq.tables.ContestQuestions rename(java.lang.String name) {
		return new org.ng200.openolympus.jooq.tables.ContestQuestions(name, null);
	}
}
