/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contests extends org.jooq.impl.TableImpl<org.ng200.openolympus.jooq.tables.records.ContestsRecord> {

	private static final long serialVersionUID = 1907839817;

	/**
	 * The reference instance of <code>public.contests</code>
	 */
	public static final org.ng200.openolympus.jooq.tables.Contests CONTESTS = new org.ng200.openolympus.jooq.tables.Contests();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ng200.openolympus.jooq.tables.records.ContestsRecord> getRecordType() {
		return org.ng200.openolympus.jooq.tables.records.ContestsRecord.class;
	}

	/**
	 * The column <code>public.contests.id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.contests.created_date</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestsRecord, java.sql.Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.contests.duration</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestsRecord, java.lang.Long> DURATION = createField("duration", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.contests.last_modified_date</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestsRecord, java.sql.Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.contests.name</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.contests.start_time</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestsRecord, java.sql.Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.contests.created_by_id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestsRecord, java.lang.Long> CREATED_BY_ID = createField("created_by_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.contests.last_modified_by_id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestsRecord, java.lang.Long> LAST_MODIFIED_BY_ID = createField("last_modified_by_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.contests</code> table reference
	 */
	public Contests() {
		this("contests", null);
	}

	/**
	 * Create an aliased <code>public.contests</code> table reference
	 */
	public Contests(java.lang.String alias) {
		this(alias, org.ng200.openolympus.jooq.tables.Contests.CONTESTS);
	}

	private Contests(java.lang.String alias, org.jooq.Table<org.ng200.openolympus.jooq.tables.records.ContestsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Contests(java.lang.String alias, org.jooq.Table<org.ng200.openolympus.jooq.tables.records.ContestsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ng200.openolympus.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.ContestsRecord> getPrimaryKey() {
		return org.ng200.openolympus.jooq.Keys.CONTESTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.ContestsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.ContestsRecord>>asList(org.ng200.openolympus.jooq.Keys.CONTESTS_PKEY, org.ng200.openolympus.jooq.Keys.UK_8RUVBF7HVS4REWEBOJY3DYWN5);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.ng200.openolympus.jooq.tables.records.ContestsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.ng200.openolympus.jooq.tables.records.ContestsRecord, ?>>asList(org.ng200.openolympus.jooq.Keys.CONTESTS__FK_FSUJ0IPXAT2ORW5P1EP57L6WF, org.ng200.openolympus.jooq.Keys.CONTESTS__FK_78JHVS11V28S8JQFIDGQ8U7KI);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ng200.openolympus.jooq.tables.Contests as(java.lang.String alias) {
		return new org.ng200.openolympus.jooq.tables.Contests(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ng200.openolympus.jooq.tables.Contests rename(java.lang.String name) {
		return new org.ng200.openolympus.jooq.tables.Contests(name, null);
	}
}
