/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContestMessages extends org.jooq.impl.TableImpl<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord> {

	private static final long serialVersionUID = -771818398;

	/**
	 * The reference instance of <code>public.contest_messages</code>
	 */
	public static final org.ng200.openolympus.jooq.tables.ContestMessages CONTEST_MESSAGES = new org.ng200.openolympus.jooq.tables.ContestMessages();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord> getRecordType() {
		return org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord.class;
	}

	/**
	 * The column <code>public.contest_messages.id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.contest_messages.created_date</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, java.sql.Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.contest_messages.last_modified_date</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, java.sql.Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.contest_messages.question</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, java.lang.String> QUESTION = createField("question", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.contest_messages.response</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, java.lang.String> RESPONSE = createField("response", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.contest_messages.contest_id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, java.lang.Long> CONTEST_ID = createField("contest_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.contest_messages.created_by_id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, java.lang.Long> CREATED_BY_ID = createField("created_by_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.contest_messages.last_modified_by_id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, java.lang.Long> LAST_MODIFIED_BY_ID = createField("last_modified_by_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.contest_messages</code> table reference
	 */
	public ContestMessages() {
		this("contest_messages", null);
	}

	/**
	 * Create an aliased <code>public.contest_messages</code> table reference
	 */
	public ContestMessages(java.lang.String alias) {
		this(alias, org.ng200.openolympus.jooq.tables.ContestMessages.CONTEST_MESSAGES);
	}

	private ContestMessages(java.lang.String alias, org.jooq.Table<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ContestMessages(java.lang.String alias, org.jooq.Table<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ng200.openolympus.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord> getPrimaryKey() {
		return org.ng200.openolympus.jooq.Keys.CONTEST_MESSAGES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord>>asList(org.ng200.openolympus.jooq.Keys.CONTEST_MESSAGES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.ng200.openolympus.jooq.tables.records.ContestMessagesRecord, ?>>asList(org.ng200.openolympus.jooq.Keys.CONTEST_MESSAGES__FK_969ILBCNDR11F6CX3RYMN2INN, org.ng200.openolympus.jooq.Keys.CONTEST_MESSAGES__FK_F44KEEQD8YFHV9DM8H1D5RBI2, org.ng200.openolympus.jooq.Keys.CONTEST_MESSAGES__FK_BER2W2OEH679WF03M3CVAVRKY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ng200.openolympus.jooq.tables.ContestMessages as(java.lang.String alias) {
		return new org.ng200.openolympus.jooq.tables.ContestMessages(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ng200.openolympus.jooq.tables.ContestMessages rename(java.lang.String name) {
		return new org.ng200.openolympus.jooq.tables.ContestMessages(name, null);
	}
}
