/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles extends org.jooq.impl.TableImpl<org.ng200.openolympus.jooq.tables.records.UserRolesRecord> {

	private static final long serialVersionUID = -2145319102;

	/**
	 * The reference instance of <code>public.user_roles</code>
	 */
	public static final org.ng200.openolympus.jooq.tables.UserRoles USER_ROLES = new org.ng200.openolympus.jooq.tables.UserRoles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ng200.openolympus.jooq.tables.records.UserRolesRecord> getRecordType() {
		return org.ng200.openolympus.jooq.tables.records.UserRolesRecord.class;
	}

	/**
	 * The column <code>public.user_roles.id</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.UserRolesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.user_roles.display_name</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.UserRolesRecord, java.lang.String> DISPLAY_NAME = createField("display_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.user_roles.role_name</code>.
	 */
	public final org.jooq.TableField<org.ng200.openolympus.jooq.tables.records.UserRolesRecord, java.lang.String> ROLE_NAME = createField("role_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>public.user_roles</code> table reference
	 */
	public UserRoles() {
		this("user_roles", null);
	}

	/**
	 * Create an aliased <code>public.user_roles</code> table reference
	 */
	public UserRoles(java.lang.String alias) {
		this(alias, org.ng200.openolympus.jooq.tables.UserRoles.USER_ROLES);
	}

	private UserRoles(java.lang.String alias, org.jooq.Table<org.ng200.openolympus.jooq.tables.records.UserRolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserRoles(java.lang.String alias, org.jooq.Table<org.ng200.openolympus.jooq.tables.records.UserRolesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ng200.openolympus.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.UserRolesRecord> getPrimaryKey() {
		return org.ng200.openolympus.jooq.Keys.USER_ROLES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.UserRolesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ng200.openolympus.jooq.tables.records.UserRolesRecord>>asList(org.ng200.openolympus.jooq.Keys.USER_ROLES_PKEY, org.ng200.openolympus.jooq.Keys.UK_40FVVY071DNQY9TYWK6EI7F5R);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ng200.openolympus.jooq.tables.UserRoles as(java.lang.String alias) {
		return new org.ng200.openolympus.jooq.tables.UserRoles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ng200.openolympus.jooq.tables.UserRoles rename(java.lang.String name) {
		return new org.ng200.openolympus.jooq.tables.UserRoles(name, null);
	}
}
