/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.Duration;
import java.time.OffsetDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "contest", schema = "public")
public interface IContest extends Serializable {

	/**
	 * Setter for <code>public.contest.id</code>.
	 */
	public IContest setId(Integer value);

	/**
	 * Getter for <code>public.contest.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>public.contest.duration</code>.
	 */
	public IContest setDuration(Duration value);

	/**
	 * Getter for <code>public.contest.duration</code>.
	 */
	@Column(name = "duration", precision = 64)
	public Duration getDuration();

	/**
	 * Setter for <code>public.contest.name</code>.
	 */
	public IContest setName(String value);

	/**
	 * Getter for <code>public.contest.name</code>.
	 */
	@Column(name = "name", unique = true, length = 255)
	public String getName();

	/**
	 * Setter for <code>public.contest.show_full_tests_during_contest</code>.
	 */
	public IContest setShowFullTestsDuringContest(Boolean value);

	/**
	 * Getter for <code>public.contest.show_full_tests_during_contest</code>.
	 */
	@Column(name = "show_full_tests_during_contest", nullable = false)
	public Boolean getShowFullTestsDuringContest();

	/**
	 * Setter for <code>public.contest.start_time</code>.
	 */
	public IContest setStartTime(OffsetDateTime value);

	/**
	 * Getter for <code>public.contest.start_time</code>.
	 */
	@Column(name = "start_time")
	public OffsetDateTime getStartTime();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IContest
	 */
	public void from(org.ng200.openolympus.jooq.tables.interfaces.IContest from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IContest
	 */
	public <E extends org.ng200.openolympus.jooq.tables.interfaces.IContest> E into(E into);
}
