/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "contest_message", schema = "public")
public interface IContestMessage extends Serializable {

	/**
	 * Setter for <code>public.contest_message.id</code>.
	 */
	public IContestMessage setId(Integer value);

	/**
	 * Getter for <code>public.contest_message.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>public.contest_message.question</code>.
	 */
	public IContestMessage setQuestion(String value);

	/**
	 * Getter for <code>public.contest_message.question</code>.
	 */
	@Column(name = "question")
	public String getQuestion();

	/**
	 * Setter for <code>public.contest_message.response</code>.
	 */
	public IContestMessage setResponse(String value);

	/**
	 * Getter for <code>public.contest_message.response</code>.
	 */
	@Column(name = "response")
	public String getResponse();

	/**
	 * Setter for <code>public.contest_message.user_id</code>.
	 */
	public IContestMessage setUserId(Long value);

	/**
	 * Getter for <code>public.contest_message.user_id</code>.
	 */
	@Column(name = "user_id", nullable = false, precision = 64)
	public Long getUserId();

	/**
	 * Setter for <code>public.contest_message.contest_id</code>.
	 */
	public IContestMessage setContestId(Integer value);

	/**
	 * Getter for <code>public.contest_message.contest_id</code>.
	 */
	@Column(name = "contest_id", nullable = false, precision = 32)
	public Integer getContestId();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IContestMessage
	 */
	public void from(org.ng200.openolympus.jooq.tables.interfaces.IContestMessage from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IContestMessage
	 */
	public <E extends org.ng200.openolympus.jooq.tables.interfaces.IContestMessage> E into(E into);
}
