/**
 * The MIT License
 * Copyright (c) 2014-2016 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.Duration;
import java.time.OffsetDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "get_running_contest", schema = "public")
public interface IGetRunningContest extends Serializable {

	/**
	 * Setter for <code>public.get_running_contest.id</code>.
	 */
	public IGetRunningContest setId(Integer value);

	/**
	 * Getter for <code>public.get_running_contest.id</code>.
	 */
	@Column(name = "id", nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>public.get_running_contest.duration</code>.
	 */
	public IGetRunningContest setDuration(Duration value);

	/**
	 * Getter for <code>public.get_running_contest.duration</code>.
	 */
	@Column(name = "duration", precision = 64)
	public Duration getDuration();

	/**
	 * Setter for <code>public.get_running_contest.name</code>.
	 */
	public IGetRunningContest setName(String value);

	/**
	 * Getter for <code>public.get_running_contest.name</code>.
	 */
	@Column(name = "name", length = 255)
	public String getName();

	/**
	 * Setter for <code>public.get_running_contest.show_full_tests_during_contest</code>.
	 */
	public IGetRunningContest setShowFullTestsDuringContest(Boolean value);

	/**
	 * Getter for <code>public.get_running_contest.show_full_tests_during_contest</code>.
	 */
	@Column(name = "show_full_tests_during_contest", nullable = false)
	public Boolean getShowFullTestsDuringContest();

	/**
	 * Setter for <code>public.get_running_contest.start_time</code>.
	 */
	public IGetRunningContest setStartTime(OffsetDateTime value);

	/**
	 * Getter for <code>public.get_running_contest.start_time</code>.
	 */
	@Column(name = "start_time")
	public OffsetDateTime getStartTime();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IGetRunningContest
	 */
	public void from(org.ng200.openolympus.jooq.tables.interfaces.IGetRunningContest from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IGetRunningContest
	 */
	public <E extends org.ng200.openolympus.jooq.tables.interfaces.IGetRunningContest> E into(E into);
}
