/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.interfaces;

import java.io.Serializable;
import java.sql.Timestamp;
import java.time.Duration;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
						"http://www.jooq.org",
						"jOOQ version:3.6.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
					"all",
					"unchecked",
					"rawtypes"
})
@Entity
@Table(name = "get_contests_that_intersect", schema = "public")
public interface IGetContestsThatIntersect extends Serializable {

	/**
	 * Load data from another generated Record/POJO implementing the common
	 * interface IGetContestsThatIntersect
	 */
	public void from(
			org.ng200.openolympus.jooq.tables.interfaces.IGetContestsThatIntersect from);

	/**
	 * Getter for <code>public.get_contests_that_intersect.duration</code>.
	 */
	@Column(name = "duration", precision = 64)
	public Duration getDuration();

	/**
	 * Getter for <code>public.get_contests_that_intersect.id</code>.
	 */
	@Column(name = "id", nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Getter for <code>public.get_contests_that_intersect.name</code>.
	 */
	@Column(name = "name", length = 255)
	public String getName();

	/**
	 * Getter for
	 * <code>public.get_contests_that_intersect.show_full_tests_during_contest</code>
	 * .
	 */
	@Column(name = "show_full_tests_during_contest", nullable = false)
	public Boolean getShowFullTestsDuringContest();

	/**
	 * Getter for <code>public.get_contests_that_intersect.start_time</code>.
	 */
	@Column(name = "start_time")
	public Timestamp getStartTime();

	/**
	 * Copy data into another generated Record/POJO implementing the common
	 * interface IGetContestsThatIntersect
	 */
	public <E extends org.ng200.openolympus.jooq.tables.interfaces.IGetContestsThatIntersect> E into(
			E into);

	/**
	 * Setter for <code>public.get_contests_that_intersect.duration</code>.
	 */
	public IGetContestsThatIntersect setDuration(Duration value);

	/**
	 * Setter for <code>public.get_contests_that_intersect.id</code>.
	 */
	public IGetContestsThatIntersect setId(Integer value);

	/**
	 * Setter for <code>public.get_contests_that_intersect.name</code>.
	 */
	public IGetContestsThatIntersect setName(String value);

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Setter for
	 * <code>public.get_contests_that_intersect.show_full_tests_during_contest</code>
	 * .
	 */
	public IGetContestsThatIntersect setShowFullTestsDuringContest(
			Boolean value);

	/**
	 * Setter for <code>public.get_contests_that_intersect.start_time</code>.
	 */
	public IGetContestsThatIntersect setStartTime(Timestamp value);
}
