/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "group_users", schema = "public", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"group_id", "user_id"})
})
public interface IGroupUsers extends Serializable {

	/**
	 * Setter for <code>public.group_users.can_add_others_to_group</code>.
	 */
	public IGroupUsers setCanAddOthersToGroup(Boolean value);

	/**
	 * Getter for <code>public.group_users.can_add_others_to_group</code>.
	 */
	@Column(name = "can_add_others_to_group", nullable = false)
	public Boolean getCanAddOthersToGroup();

	/**
	 * Setter for <code>public.group_users.group_id</code>.
	 */
	public IGroupUsers setGroupId(Long value);

	/**
	 * Getter for <code>public.group_users.group_id</code>.
	 */
	@Column(name = "group_id", nullable = false, precision = 64)
	public Long getGroupId();

	/**
	 * Setter for <code>public.group_users.user_id</code>.
	 */
	public IGroupUsers setUserId(Long value);

	/**
	 * Getter for <code>public.group_users.user_id</code>.
	 */
	@Column(name = "user_id", nullable = false, precision = 64)
	public Long getUserId();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IGroupUsers
	 */
	public void from(org.ng200.openolympus.jooq.tables.interfaces.IGroupUsers from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IGroupUsers
	 */
	public <E extends org.ng200.openolympus.jooq.tables.interfaces.IGroupUsers> E into(E into);
}
