/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.interfaces;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
						"http://www.jooq.org",
						"jOOQ version:3.6.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
					"all",
					"unchecked",
					"rawtypes"
})
@Entity
@Table(name = "task", schema = "public")
public interface ITask extends Serializable {

	/**
	 * Load data from another generated Record/POJO implementing the common
	 * interface ITask
	 */
	public void from(org.ng200.openolympus.jooq.tables.interfaces.ITask from);

	/**
	 * Getter for <code>public.task.created_date</code>.
	 */
	@Column(name = "created_date")
	public LocalDateTime getCreatedDate();

	/**
	 * Getter for <code>public.task.description_file</code>.
	 */
	@Column(name = "description_file", nullable = false)
	public String getDescriptionFile();

	/**
	 * Getter for <code>public.task.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Getter for <code>public.task.name</code>.
	 */
	@Column(name = "name", unique = true, length = 255)
	public String getName();

	/**
	 * Getter for <code>public.task.task_location</code>.
	 */
	@Column(name = "task_location", nullable = false)
	public String getTaskLocation();

	/**
	 * Copy data into another generated Record/POJO implementing the common
	 * interface ITask
	 */
	public <E extends org.ng200.openolympus.jooq.tables.interfaces.ITask> E into(
			E into);

	/**
	 * Setter for <code>public.task.created_date</code>.
	 */
	public ITask setCreatedDate(LocalDateTime value);

	/**
	 * Setter for <code>public.task.description_file</code>.
	 */
	public ITask setDescriptionFile(String value);

	/**
	 * Setter for <code>public.task.id</code>.
	 */
	public ITask setId(Integer value);

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>public.task.name</code>.
	 */
	public ITask setName(String value);

	/**
	 * Setter for <code>public.task.task_location</code>.
	 */
	public ITask setTaskLocation(String value);
}
