/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.interfaces;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
						"http://www.jooq.org",
						"jOOQ version:3.6.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
					"all",
					"unchecked",
					"rawtypes"
})
@Entity
@Table(name = "USER", schema = "public")
public interface IUser extends Serializable {

	/**
	 * Load data from another generated Record/POJO implementing the common
	 * interface IUser
	 */
	public void from(org.ng200.openolympus.jooq.tables.interfaces.IUser from);

	/**
	 * Getter for <code>public.USER.address_city</code>.
	 */
	@Column(name = "address_city", length = 255)
	public String getAddressCity();

	/**
	 * Getter for <code>public.USER.address_country</code>.
	 */
	@Column(name = "address_country", length = 255)
	public String getAddressCountry();

	/**
	 * Getter for <code>public.USER.address_line1</code>.
	 */
	@Column(name = "address_line1")
	public String getAddressLine1();

	/**
	 * Getter for <code>public.USER.address_line2</code>.
	 */
	@Column(name = "address_line2")
	public String getAddressLine2();

	/**
	 * Getter for <code>public.USER.address_state</code>.
	 */
	@Column(name = "address_state", length = 255)
	public String getAddressState();

	/**
	 * Getter for <code>public.USER.approval_email_sent</code>.
	 */
	@Column(name = "approval_email_sent", nullable = false)
	public Boolean getApprovalEmailSent();

	/**
	 * Getter for <code>public.USER.approved</code>.
	 */
	@Column(name = "approved", nullable = false)
	public Boolean getApproved();

	/**
	 * Getter for <code>public.USER.birth_date</code>.
	 */
	@Column(name = "birth_date")
	public Timestamp getBirthDate();

	/**
	 * Getter for <code>public.USER.email_address</code>.
	 */
	@Column(name = "email_address", length = 255)
	public String getEmailAddress();

	/**
	 * Getter for <code>public.USER.email_confirmation_token</code>.
	 */
	@Column(name = "email_confirmation_token", length = 255)
	public String getEmailConfirmationToken();

	/**
	 * Getter for <code>public.USER.enabled</code>.
	 */
	@Column(name = "enabled", nullable = false)
	public Boolean getEnabled();

	/**
	 * Getter for <code>public.USER.first_name_localised</code>.
	 */
	@Column(name = "first_name_localised", length = 255)
	public String getFirstNameLocalised();

	/**
	 * Getter for <code>public.USER.first_name_main</code>.
	 */
	@Column(name = "first_name_main", length = 255)
	public String getFirstNameMain();

	/**
	 * Getter for <code>public.USER.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 64)
	public Long getId();

	/**
	 * Getter for <code>public.USER.landline</code>.
	 */
	@Column(name = "landline", length = 255)
	public String getLandline();

	/**
	 * Getter for <code>public.USER.last_name_localised</code>.
	 */
	@Column(name = "last_name_localised", length = 255)
	public String getLastNameLocalised();

	/**
	 * Getter for <code>public.USER.last_name_main</code>.
	 */
	@Column(name = "last_name_main", length = 255)
	public String getLastNameMain();

	/**
	 * Getter for <code>public.USER.middle_name_localised</code>.
	 */
	@Column(name = "middle_name_localised", length = 255)
	public String getMiddleNameLocalised();

	/**
	 * Getter for <code>public.USER.middle_name_main</code>.
	 */
	@Column(name = "middle_name_main", length = 255)
	public String getMiddleNameMain();

	/**
	 * Getter for <code>public.USER.mobile</code>.
	 */
	@Column(name = "mobile", length = 255)
	public String getMobile();

	/**
	 * Getter for <code>public.USER.password</code>.
	 */
	@Column(name = "password", length = 255)
	public String getPassword();

	/**
	 * Getter for <code>public.USER.school</code>.
	 */
	@Column(name = "school", length = 255)
	public String getSchool();

	/**
	 * Getter for <code>public.USER.superuser</code>.
	 */
	@Column(name = "superuser", nullable = false)
	public Boolean getSuperuser();

	/**
	 * Getter for <code>public.USER.teacher_first_name</code>.
	 */
	@Column(name = "teacher_first_name", length = 255)
	public String getTeacherFirstName();

	/**
	 * Getter for <code>public.USER.teacher_last_name</code>.
	 */
	@Column(name = "teacher_last_name", length = 255)
	public String getTeacherLastName();

	/**
	 * Getter for <code>public.USER.teacher_middle_name</code>.
	 */
	@Column(name = "teacher_middle_name", length = 255)
	public String getTeacherMiddleName();

	/**
	 * Getter for <code>public.USER.username</code>.
	 */
	@Column(name = "username", unique = true, length = 255)
	public String getUsername();

	/**
	 * Copy data into another generated Record/POJO implementing the common
	 * interface IUser
	 */
	public <E extends org.ng200.openolympus.jooq.tables.interfaces.IUser> E into(
			E into);

	/**
	 * Setter for <code>public.USER.address_city</code>.
	 */
	public IUser setAddressCity(String value);

	/**
	 * Setter for <code>public.USER.address_country</code>.
	 */
	public IUser setAddressCountry(String value);

	/**
	 * Setter for <code>public.USER.address_line1</code>.
	 */
	public IUser setAddressLine1(String value);

	/**
	 * Setter for <code>public.USER.address_line2</code>.
	 */
	public IUser setAddressLine2(String value);

	/**
	 * Setter for <code>public.USER.address_state</code>.
	 */
	public IUser setAddressState(String value);

	/**
	 * Setter for <code>public.USER.approval_email_sent</code>.
	 */
	public IUser setApprovalEmailSent(Boolean value);

	/**
	 * Setter for <code>public.USER.approved</code>.
	 */
	public IUser setApproved(Boolean value);

	/**
	 * Setter for <code>public.USER.birth_date</code>.
	 */
	public IUser setBirthDate(Timestamp value);

	/**
	 * Setter for <code>public.USER.email_address</code>.
	 */
	public IUser setEmailAddress(String value);

	/**
	 * Setter for <code>public.USER.email_confirmation_token</code>.
	 */
	public IUser setEmailConfirmationToken(String value);

	/**
	 * Setter for <code>public.USER.enabled</code>.
	 */
	public IUser setEnabled(Boolean value);

	/**
	 * Setter for <code>public.USER.first_name_localised</code>.
	 */
	public IUser setFirstNameLocalised(String value);

	/**
	 * Setter for <code>public.USER.first_name_main</code>.
	 */
	public IUser setFirstNameMain(String value);

	/**
	 * Setter for <code>public.USER.id</code>.
	 */
	public IUser setId(Long value);

	/**
	 * Setter for <code>public.USER.landline</code>.
	 */
	public IUser setLandline(String value);

	/**
	 * Setter for <code>public.USER.last_name_localised</code>.
	 */
	public IUser setLastNameLocalised(String value);

	/**
	 * Setter for <code>public.USER.last_name_main</code>.
	 */
	public IUser setLastNameMain(String value);

	/**
	 * Setter for <code>public.USER.middle_name_localised</code>.
	 */
	public IUser setMiddleNameLocalised(String value);

	/**
	 * Setter for <code>public.USER.middle_name_main</code>.
	 */
	public IUser setMiddleNameMain(String value);

	/**
	 * Setter for <code>public.USER.mobile</code>.
	 */
	public IUser setMobile(String value);

	/**
	 * Setter for <code>public.USER.password</code>.
	 */
	public IUser setPassword(String value);

	/**
	 * Setter for <code>public.USER.school</code>.
	 */
	public IUser setSchool(String value);

	/**
	 * Setter for <code>public.USER.superuser</code>.
	 */
	public IUser setSuperuser(Boolean value);

	/**
	 * Setter for <code>public.USER.teacher_first_name</code>.
	 */
	public IUser setTeacherFirstName(String value);

	/**
	 * Setter for <code>public.USER.teacher_last_name</code>.
	 */
	public IUser setTeacherLastName(String value);

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>public.USER.teacher_middle_name</code>.
	 */
	public IUser setTeacherMiddleName(String value);

	/**
	 * Setter for <code>public.USER.username</code>.
	 */
	public IUser setUsername(String value);
}
