/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.ng200.openolympus.jooq.tables.interfaces.IContestMessage;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "contest_message", schema = "public")
public class ContestMessage implements IContestMessage {

	private static final long serialVersionUID = -1071337658;

	private Integer id;
	private String  question;
	private String  response;
	private Long    userId;
	private Integer contestId;

	public ContestMessage() {}

	public ContestMessage(ContestMessage value) {
		this.id = value.id;
		this.question = value.question;
		this.response = value.response;
		this.userId = value.userId;
		this.contestId = value.contestId;
	}

	public ContestMessage(
		Integer id,
		String  question,
		String  response,
		Long    userId,
		Integer contestId
	) {
		this.id = id;
		this.question = question;
		this.response = response;
		this.userId = userId;
		this.contestId = contestId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public ContestMessage setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "question")
	@Override
	public String getQuestion() {
		return this.question;
	}

	@Override
	public ContestMessage setQuestion(String question) {
		this.question = question;
		return this;
	}

	@Column(name = "response")
	@Override
	public String getResponse() {
		return this.response;
	}

	@Override
	public ContestMessage setResponse(String response) {
		this.response = response;
		return this;
	}

	@Column(name = "user_id", nullable = false, precision = 64)
	@Override
	public Long getUserId() {
		return this.userId;
	}

	@Override
	public ContestMessage setUserId(Long userId) {
		this.userId = userId;
		return this;
	}

	@Column(name = "contest_id", nullable = false, precision = 32)
	@Override
	public Integer getContestId() {
		return this.contestId;
	}

	@Override
	public ContestMessage setContestId(Integer contestId) {
		this.contestId = contestId;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IContestMessage from) {
		setId(from.getId());
		setQuestion(from.getQuestion());
		setResponse(from.getResponse());
		setUserId(from.getUserId());
		setContestId(from.getContestId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IContestMessage> E into(E into) {
		into.from(this);
		return into;
	}
}
