/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.ng200.openolympus.jooq.tables.interfaces.IContestPermissionPrincipal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "contest_permission_principal", schema = "public")
public class ContestPermissionPrincipal implements IContestPermissionPrincipal {

	private static final long serialVersionUID = -723070328;

	private Integer principalId;
	private Long    contestPermissionId;

	public ContestPermissionPrincipal() {}

	public ContestPermissionPrincipal(ContestPermissionPrincipal value) {
		this.principalId = value.principalId;
		this.contestPermissionId = value.contestPermissionId;
	}

	public ContestPermissionPrincipal(
		Integer principalId,
		Long    contestPermissionId
	) {
		this.principalId = principalId;
		this.contestPermissionId = contestPermissionId;
	}

	@Column(name = "principal_id", precision = 32)
	@Override
	public Integer getPrincipalId() {
		return this.principalId;
	}

	@Override
	public ContestPermissionPrincipal setPrincipalId(Integer principalId) {
		this.principalId = principalId;
		return this;
	}

	@Id
	@Column(name = "contest_permission_id", unique = true, nullable = false, precision = 64)
	@Override
	public Long getContestPermissionId() {
		return this.contestPermissionId;
	}

	@Override
	public ContestPermissionPrincipal setContestPermissionId(Long contestPermissionId) {
		this.contestPermissionId = contestPermissionId;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IContestPermissionPrincipal from) {
		setPrincipalId(from.getPrincipalId());
		setContestPermissionId(from.getContestPermissionId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IContestPermissionPrincipal> E into(E into) {
		into.from(this);
		return into;
	}
}
