/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.ng200.openolympus.jooq.tables.interfaces.IResource;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "resource", schema = "public")
public class Resource implements IResource {

	private static final long serialVersionUID = 944037971;

	private Long    id;
	private String  name;
	private String  filename;
	private Long    userId;
	private Integer taskId;

	public Resource() {}

	public Resource(Resource value) {
		this.id = value.id;
		this.name = value.name;
		this.filename = value.filename;
		this.userId = value.userId;
		this.taskId = value.taskId;
	}

	public Resource(
		Long    id,
		String  name,
		String  filename,
		Long    userId,
		Integer taskId
	) {
		this.id = id;
		this.name = name;
		this.filename = filename;
		this.userId = userId;
		this.taskId = taskId;
	}

	@Column(name = "id", nullable = false, precision = 64)
	@Override
	public Long getId() {
		return this.id;
	}

	@Override
	public Resource setId(Long id) {
		this.id = id;
		return this;
	}

	@Column(name = "name", nullable = false)
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public Resource setName(String name) {
		this.name = name;
		return this;
	}

	@Column(name = "filename", nullable = false)
	@Override
	public String getFilename() {
		return this.filename;
	}

	@Override
	public Resource setFilename(String filename) {
		this.filename = filename;
		return this;
	}

	@Column(name = "USER_id", precision = 64)
	@Override
	public Long getUserId() {
		return this.userId;
	}

	@Override
	public Resource setUserId(Long userId) {
		this.userId = userId;
		return this;
	}

	@Column(name = "task_id", precision = 32)
	@Override
	public Integer getTaskId() {
		return this.taskId;
	}

	@Override
	public Resource setTaskId(Integer taskId) {
		this.taskId = taskId;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IResource from) {
		setId(from.getId());
		setName(from.getName());
		setFilename(from.getFilename());
		setUserId(from.getUserId());
		setTaskId(from.getTaskId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IResource> E into(E into) {
		into.from(this);
		return into;
	}
}
