/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.ng200.openolympus.jooq.enums.VerdictStatusType;
import org.ng200.openolympus.jooq.tables.interfaces.ITaskPermission;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "task_permission", schema = "public")
public class TaskPermission implements ITaskPermission {

	private static final long serialVersionUID = 904553393;

	private Long              id;
	private VerdictStatusType type;
	private Integer           taskId;

	public TaskPermission() {}

	public TaskPermission(TaskPermission value) {
		this.id = value.id;
		this.type = value.type;
		this.taskId = value.taskId;
	}

	public TaskPermission(
		Long              id,
		VerdictStatusType type,
		Integer           taskId
	) {
		this.id = id;
		this.type = type;
		this.taskId = taskId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 64)
	@Override
	public Long getId() {
		return this.id;
	}

	@Override
	public TaskPermission setId(Long id) {
		this.id = id;
		return this;
	}

	@Column(name = "type", nullable = false)
	@Override
	public VerdictStatusType getType() {
		return this.type;
	}

	@Override
	public TaskPermission setType(VerdictStatusType type) {
		this.type = type;
		return this;
	}

	@Column(name = "task_id", precision = 32)
	@Override
	public Integer getTaskId() {
		return this.taskId;
	}

	@Override
	public TaskPermission setTaskId(Integer taskId) {
		this.taskId = taskId;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ITaskPermission from) {
		setId(from.getId());
		setType(from.getType());
		setTaskId(from.getTaskId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ITaskPermission> E into(E into) {
		into.from(this);
		return into;
	}
}
