/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContestQuestionsRecord extends org.jooq.impl.UpdatableRecordImpl<org.ng200.openolympus.jooq.tables.records.ContestQuestionsRecord> implements org.jooq.Record5<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 186175714;

	/**
	 * Setter for <code>public.contest_questions.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.contest_questions.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.contest_questions.question</code>.
	 */
	public void setQuestion(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.contest_questions.question</code>.
	 */
	public java.lang.String getQuestion() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.contest_questions.response</code>.
	 */
	public void setResponse(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.contest_questions.response</code>.
	 */
	public java.lang.String getResponse() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.contest_questions.contest_id</code>.
	 */
	public void setContestId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.contest_questions.contest_id</code>.
	 */
	public java.lang.Long getContestId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>public.contest_questions.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.contest_questions.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.ng200.openolympus.jooq.tables.ContestQuestions.CONTEST_QUESTIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.ng200.openolympus.jooq.tables.ContestQuestions.CONTEST_QUESTIONS.QUESTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.ng200.openolympus.jooq.tables.ContestQuestions.CONTEST_QUESTIONS.RESPONSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return org.ng200.openolympus.jooq.tables.ContestQuestions.CONTEST_QUESTIONS.CONTEST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return org.ng200.openolympus.jooq.tables.ContestQuestions.CONTEST_QUESTIONS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getQuestion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getResponse();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getContestId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContestQuestionsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContestQuestionsRecord value2(java.lang.String value) {
		setQuestion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContestQuestionsRecord value3(java.lang.String value) {
		setResponse(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContestQuestionsRecord value4(java.lang.Long value) {
		setContestId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContestQuestionsRecord value5(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContestQuestionsRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.Long value4, java.lang.Long value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContestQuestionsRecord
	 */
	public ContestQuestionsRecord() {
		super(org.ng200.openolympus.jooq.tables.ContestQuestions.CONTEST_QUESTIONS);
	}

	/**
	 * Create a detached, initialised ContestQuestionsRecord
	 */
	public ContestQuestionsRecord(java.lang.Long id, java.lang.String question, java.lang.String response, java.lang.Long contestId, java.lang.Long userId) {
		super(org.ng200.openolympus.jooq.tables.ContestQuestions.CONTEST_QUESTIONS);

		setValue(0, id);
		setValue(1, question);
		setValue(2, response);
		setValue(3, contestId);
		setValue(4, userId);
	}
}
