/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeExtensionsRecord extends org.jooq.impl.UpdatableRecordImpl<org.ng200.openolympus.jooq.tables.records.TimeExtensionsRecord> implements org.jooq.Record6<java.lang.Long, java.sql.Timestamp, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 1896101879;

	/**
	 * Setter for <code>public.time_extensions.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.time_extensions.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.time_extensions.created_date</code>.
	 */
	public void setCreatedDate(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.time_extensions.created_date</code>.
	 */
	public java.sql.Timestamp getCreatedDate() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>public.time_extensions.duration</code>.
	 */
	public void setDuration(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.time_extensions.duration</code>.
	 */
	public java.lang.Long getDuration() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>public.time_extensions.contest_id</code>.
	 */
	public void setContestId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.time_extensions.contest_id</code>.
	 */
	public java.lang.Long getContestId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>public.time_extensions.created_by_id</code>.
	 */
	public void setCreatedById(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.time_extensions.created_by_id</code>.
	 */
	public java.lang.Long getCreatedById() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>public.time_extensions.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.time_extensions.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.sql.Timestamp, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.sql.Timestamp, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.ng200.openolympus.jooq.tables.TimeExtensions.TIME_EXTENSIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return org.ng200.openolympus.jooq.tables.TimeExtensions.TIME_EXTENSIONS.CREATED_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return org.ng200.openolympus.jooq.tables.TimeExtensions.TIME_EXTENSIONS.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return org.ng200.openolympus.jooq.tables.TimeExtensions.TIME_EXTENSIONS.CONTEST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return org.ng200.openolympus.jooq.tables.TimeExtensions.TIME_EXTENSIONS.CREATED_BY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return org.ng200.openolympus.jooq.tables.TimeExtensions.TIME_EXTENSIONS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getCreatedDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getContestId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getCreatedById();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionsRecord value2(java.sql.Timestamp value) {
		setCreatedDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionsRecord value3(java.lang.Long value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionsRecord value4(java.lang.Long value) {
		setContestId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionsRecord value5(java.lang.Long value) {
		setCreatedById(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionsRecord value6(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtensionsRecord values(java.lang.Long value1, java.sql.Timestamp value2, java.lang.Long value3, java.lang.Long value4, java.lang.Long value5, java.lang.Long value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TimeExtensionsRecord
	 */
	public TimeExtensionsRecord() {
		super(org.ng200.openolympus.jooq.tables.TimeExtensions.TIME_EXTENSIONS);
	}

	/**
	 * Create a detached, initialised TimeExtensionsRecord
	 */
	public TimeExtensionsRecord(java.lang.Long id, java.sql.Timestamp createdDate, java.lang.Long duration, java.lang.Long contestId, java.lang.Long createdById, java.lang.Long userId) {
		super(org.ng200.openolympus.jooq.tables.TimeExtensions.TIME_EXTENSIONS);

		setValue(0, id);
		setValue(1, createdDate);
		setValue(2, duration);
		setValue(3, contestId);
		setValue(4, createdById);
		setValue(5, userId);
	}
}
