/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRolesRecord extends org.jooq.impl.UpdatableRecordImpl<org.ng200.openolympus.jooq.tables.records.UserRolesRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1228425799;

	/**
	 * Setter for <code>public.user_roles.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.user_roles.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.user_roles.display_name</code>.
	 */
	public void setDisplayName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.user_roles.display_name</code>.
	 */
	public java.lang.String getDisplayName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.user_roles.role_name</code>.
	 */
	public void setRoleName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.user_roles.role_name</code>.
	 */
	public java.lang.String getRoleName() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.ng200.openolympus.jooq.tables.UserRoles.USER_ROLES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.ng200.openolympus.jooq.tables.UserRoles.USER_ROLES.DISPLAY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.ng200.openolympus.jooq.tables.UserRoles.USER_ROLES.ROLE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDisplayName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getRoleName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord value2(java.lang.String value) {
		setDisplayName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord value3(java.lang.String value) {
		setRoleName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRolesRecord
	 */
	public UserRolesRecord() {
		super(org.ng200.openolympus.jooq.tables.UserRoles.USER_ROLES);
	}

	/**
	 * Create a detached, initialised UserRolesRecord
	 */
	public UserRolesRecord(java.lang.Long id, java.lang.String displayName, java.lang.String roleName) {
		super(org.ng200.openolympus.jooq.tables.UserRoles.USER_ROLES);

		setValue(0, id);
		setValue(1, displayName);
		setValue(2, roleName);
	}
}
