/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.ng200.openolympus.jooq.enums.VerdictStatusTypeCp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "contest_permission", schema = "public")
public interface IContestPermission extends Serializable {

	/**
	 * Setter for <code>public.contest_permission.id</code>.
	 */
	public IContestPermission setId(Long value);

	/**
	 * Getter for <code>public.contest_permission.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 64)
	public Long getId();

	/**
	 * Setter for <code>public.contest_permission.type</code>.
	 */
	public IContestPermission setType(VerdictStatusTypeCp value);

	/**
	 * Getter for <code>public.contest_permission.type</code>.
	 */
	@Column(name = "type", nullable = false)
	public VerdictStatusTypeCp getType();

	/**
	 * Setter for <code>public.contest_permission.contest_id</code>.
	 */
	public IContestPermission setContestId(Integer value);

	/**
	 * Getter for <code>public.contest_permission.contest_id</code>.
	 */
	@Column(name = "contest_id", precision = 32)
	public Integer getContestId();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IContestPermission
	 */
	public void from(org.ng200.openolympus.jooq.tables.interfaces.IContestPermission from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IContestPermission
	 */
	public <E extends org.ng200.openolympus.jooq.tables.interfaces.IContestPermission> E into(E into);
}
