/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.ng200.openolympus.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddToGroup extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -2009143548;

	/**
	 * The parameter <code>public.add_to_group.group_id_p</code>.
	 */
	public static final Parameter<Long> GROUP_ID_P = createParameter("group_id_p", org.jooq.impl.SQLDataType.BIGINT, false);

	/**
	 * The parameter <code>public.add_to_group.user_id_p</code>.
	 */
	public static final Parameter<Long> USER_ID_P = createParameter("user_id_p", org.jooq.impl.SQLDataType.BIGINT, false);

	/**
	 * Create a new routine call instance
	 */
	public AddToGroup() {
		super("add_to_group", Public.PUBLIC);

		addInParameter(GROUP_ID_P);
		addInParameter(USER_ID_P);
	}

	/**
	 * Set the <code>group_id_p</code> parameter IN value to the routine
	 */
	public void setGroupIdP(Long value) {
		setValue(GROUP_ID_P, value);
	}

	/**
	 * Set the <code>user_id_p</code> parameter IN value to the routine
	 */
	public void setUserIdP(Long value) {
		setValue(USER_ID_P, value);
	}
}
