/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.routines;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.ng200.openolympus.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetContestStartForUser extends AbstractRoutine<Timestamp> {

	private static final long serialVersionUID = 641649018;

	/**
	 * The parameter <code>public.get_contest_start_for_user.RETURN_VALUE</code>.
	 */
	public static final Parameter<Timestamp> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.TIMESTAMP, false);

	/**
	 * The parameter <code>public.get_contest_start_for_user.contest_id</code>.
	 */
	public static final Parameter<Integer> CONTEST_ID = createParameter("contest_id", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>public.get_contest_start_for_user.user_id</code>.
	 */
	public static final Parameter<Long> USER_ID = createParameter("user_id", org.jooq.impl.SQLDataType.BIGINT, false);

	/**
	 * Create a new routine call instance
	 */
	public GetContestStartForUser() {
		super("get_contest_start_for_user", Public.PUBLIC, org.jooq.impl.SQLDataType.TIMESTAMP);

		setReturnParameter(RETURN_VALUE);
		addInParameter(CONTEST_ID);
		addInParameter(USER_ID);
	}

	/**
	 * Set the <code>contest_id</code> parameter IN value to the routine
	 */
	public void setContestId(Integer value) {
		setValue(CONTEST_ID, value);
	}

	/**
	 * Set the <code>contest_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public GetContestStartForUser setContestId(Field<Integer> field) {
		setField(CONTEST_ID, field);
		return this;
	}

	/**
	 * Set the <code>user_id</code> parameter IN value to the routine
	 */
	public void setUserId(Long value) {
		setValue(USER_ID, value);
	}

	/**
	 * Set the <code>user_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public GetContestStartForUser setUserId(Field<Long> field) {
		setField(USER_ID, field);
		return this;
	}
}
