/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.routines;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.ng200.openolympus.jooq.Public;
import org.ng200.openolympus.util.DateTimeBinding;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetContestEnd extends AbstractRoutine<OffsetDateTime> {

	private static final long serialVersionUID = -1213825484;

	/**
	 * The parameter <code>public.get_contest_end.RETURN_VALUE</code>.
	 */
	public static final Parameter<OffsetDateTime> RETURN_VALUE = createParameter("RETURN_VALUE", org.ng200.openolympus.jooqsupport.CustomTypes.TIMESTAMPTZ, false, new DateTimeBinding());

	/**
	 * The parameter <code>public.get_contest_end.contest_id</code>.
	 */
	public static final Parameter<Integer> CONTEST_ID = createParameter("contest_id", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public GetContestEnd() {
		super("get_contest_end", Public.PUBLIC, org.ng200.openolympus.jooqsupport.CustomTypes.TIMESTAMPTZ, new DateTimeBinding());

		setReturnParameter(RETURN_VALUE);
		addInParameter(CONTEST_ID);
	}

	/**
	 * Set the <code>contest_id</code> parameter IN value to the routine
	 */
	public void setContestId(Integer value) {
		setValue(CONTEST_ID, value);
	}

	/**
	 * Set the <code>contest_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public GetContestEnd setContestId(Field<Integer> field) {
		setField(CONTEST_ID, field);
		return this;
	}
}
