/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.routines;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.ng200.openolympus.jooq.Public;
import org.ng200.openolympus.jooq.enums.GeneralPermissionType;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
						"http://www.jooq.org",
						"jOOQ version:3.6.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
					"all",
					"unchecked",
					"rawtypes"
})
public class HasGeneralPermission extends AbstractRoutine<Boolean> {

	private static final long serialVersionUID = -1033725084;

	/**
	 * The parameter <code>public.has_general_permission.RETURN_VALUE</code>.
	 */
	public static final Parameter<Boolean> RETURN_VALUE = AbstractRoutine
			.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BOOLEAN,
					false);

	/**
	 * The parameter <code>public.has_general_permission.principal_id_p</code>.
	 */
	public static final Parameter<Long> PRINCIPAL_ID_P = AbstractRoutine
			.createParameter("principal_id_p", org.jooq.impl.SQLDataType.BIGINT,
					false);

	/**
	 * The parameter <code>public.has_general_permission.permission_p</code>.
	 */
	public static final Parameter<GeneralPermissionType> PERMISSION_P = AbstractRoutine
			.createParameter("permission_p",
					org.jooq.util.postgres.PostgresDataType.VARCHAR
							.asEnumDataType(
									org.ng200.openolympus.jooq.enums.GeneralPermissionType.class),
					false);

	/**
	 * Create a new routine call instance
	 */
	public HasGeneralPermission() {
		super("has_general_permission", Public.PUBLIC,
				org.jooq.impl.SQLDataType.BOOLEAN);

		this.setReturnParameter(HasGeneralPermission.RETURN_VALUE);
		this.addInParameter(HasGeneralPermission.PRINCIPAL_ID_P);
		this.addInParameter(HasGeneralPermission.PERMISSION_P);
	}

	/**
	 * Set the <code>permission_p</code> parameter to the function to be used
	 * with a {@link org.jooq.Select} statement
	 */
	public HasGeneralPermission setPermissionP(
			Field<GeneralPermissionType> field) {
		this.setField(HasGeneralPermission.PERMISSION_P, field);
		return this;
	}

	/**
	 * Set the <code>permission_p</code> parameter IN value to the routine
	 */
	public void setPermissionP(GeneralPermissionType value) {
		this.setValue(HasGeneralPermission.PERMISSION_P, value);
	}

	/**
	 * Set the <code>principal_id_p</code> parameter to the function to be used
	 * with a {@link org.jooq.Select} statement
	 */
	public HasGeneralPermission setPrincipalIdP(Field<Long> field) {
		this.setField(HasGeneralPermission.PRINCIPAL_ID_P, field);
		return this;
	}

	/**
	 * Set the <code>principal_id_p</code> parameter IN value to the routine
	 */
	public void setPrincipalIdP(Long value) {
		this.setValue(HasGeneralPermission.PRINCIPAL_ID_P, value);
	}
}
