/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.routines;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.ng200.openolympus.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionAppliesToPrincipal extends AbstractRoutine<Boolean> {

	private static final long serialVersionUID = -2071669021;

	/**
	 * The parameter <code>public.permission_applies_to_principal.RETURN_VALUE</code>.
	 */
	public static final Parameter<Boolean> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BOOLEAN, false);

	/**
	 * The parameter <code>public.permission_applies_to_principal.principal_id_p</code>.
	 */
	public static final Parameter<Long> PRINCIPAL_ID_P = createParameter("principal_id_p", org.jooq.impl.SQLDataType.BIGINT, false);

	/**
	 * The parameter <code>public.permission_applies_to_principal.permission_principal_id_p</code>.
	 */
	public static final Parameter<Long> PERMISSION_PRINCIPAL_ID_P = createParameter("permission_principal_id_p", org.jooq.impl.SQLDataType.BIGINT, false);

	/**
	 * Create a new routine call instance
	 */
	public PermissionAppliesToPrincipal() {
		super("permission_applies_to_principal", Public.PUBLIC, org.jooq.impl.SQLDataType.BOOLEAN);

		setReturnParameter(RETURN_VALUE);
		addInParameter(PRINCIPAL_ID_P);
		addInParameter(PERMISSION_PRINCIPAL_ID_P);
	}

	/**
	 * Set the <code>principal_id_p</code> parameter IN value to the routine
	 */
	public void setPrincipalIdP(Long value) {
		setValue(PRINCIPAL_ID_P, value);
	}

	/**
	 * Set the <code>principal_id_p</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public PermissionAppliesToPrincipal setPrincipalIdP(Field<Long> field) {
		setField(PRINCIPAL_ID_P, field);
		return this;
	}

	/**
	 * Set the <code>permission_principal_id_p</code> parameter IN value to the routine
	 */
	public void setPermissionPrincipalIdP(Long value) {
		setValue(PERMISSION_PRINCIPAL_ID_P, value);
	}

	/**
	 * Set the <code>permission_principal_id_p</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public PermissionAppliesToPrincipal setPermissionPrincipalIdP(Field<Long> field) {
		setField(PERMISSION_PRINCIPAL_ID_P, field);
		return this;
	}
}
