/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.ng200.openolympus.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurgeGarbageContestParticipations extends AbstractRoutine<Short> {

	private static final long serialVersionUID = -709259332;

	/**
	 * The parameter <code>public.purge_garbage_contest_participations.RETURN_VALUE</code>.
	 */
	public static final Parameter<Short> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.SMALLINT, false);

	/**
	 * Create a new routine call instance
	 */
	public PurgeGarbageContestParticipations() {
		super("purge_garbage_contest_participations", Public.PUBLIC, org.jooq.impl.SQLDataType.SMALLINT);

		setReturnParameter(RETURN_VALUE);
	}
}
