/**
 * The MIT License
 * Copyright (c) 2014-2016 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.ng200.openolympus.jooq.tables.interfaces.IContestQuestion;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "contest_question", schema = "public")
public class ContestQuestion implements IContestQuestion {

	private static final long serialVersionUID = -304589842;

	private Integer id;
	private String  question;
	private String  response;
	private Long    userId;
	private Integer contestId;

	public ContestQuestion() {}

	public ContestQuestion(ContestQuestion value) {
		this.id = value.id;
		this.question = value.question;
		this.response = value.response;
		this.userId = value.userId;
		this.contestId = value.contestId;
	}

	public ContestQuestion(
		Integer id,
		String  question,
		String  response,
		Long    userId,
		Integer contestId
	) {
		this.id = id;
		this.question = question;
		this.response = response;
		this.userId = userId;
		this.contestId = contestId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public ContestQuestion setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "question")
	@Override
	public String getQuestion() {
		return this.question;
	}

	@Override
	public ContestQuestion setQuestion(String question) {
		this.question = question;
		return this;
	}

	@Column(name = "response")
	@Override
	public String getResponse() {
		return this.response;
	}

	@Override
	public ContestQuestion setResponse(String response) {
		this.response = response;
		return this;
	}

	@Column(name = "user_id", nullable = false, precision = 64)
	@Override
	public Long getUserId() {
		return this.userId;
	}

	@Override
	public ContestQuestion setUserId(Long userId) {
		this.userId = userId;
		return this;
	}

	@Column(name = "contest_id", nullable = false, precision = 32)
	@Override
	public Integer getContestId() {
		return this.contestId;
	}

	@Override
	public ContestQuestion setContestId(Integer contestId) {
		this.contestId = contestId;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ContestQuestion (");

		sb.append(id);
		sb.append(", ").append(question);
		sb.append(", ").append(response);
		sb.append(", ").append(userId);
		sb.append(", ").append(contestId);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IContestQuestion from) {
		setId(from.getId());
		setQuestion(from.getQuestion());
		setResponse(from.getResponse());
		setUserId(from.getUserId());
		setContestId(from.getContestId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IContestQuestion> E into(E into) {
		into.from(this);
		return into;
	}
}
