/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.pojos;


import java.sql.Timestamp;
import java.time.Duration;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.ng200.openolympus.jooq.tables.interfaces.IContest;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "contest", schema = "public")
public class Contest implements IContest {

	private static final long serialVersionUID = -541909947;

	private Integer   id;
	private Duration  duration;
	private String    name;
	private Boolean   showFullTestsDuringContest;
	private Timestamp startTime;
	private Long      owner;

	public Contest() {}

	public Contest(Contest value) {
		this.id = value.id;
		this.duration = value.duration;
		this.name = value.name;
		this.showFullTestsDuringContest = value.showFullTestsDuringContest;
		this.startTime = value.startTime;
		this.owner = value.owner;
	}

	public Contest(
		Integer   id,
		Duration  duration,
		String    name,
		Boolean   showFullTestsDuringContest,
		Timestamp startTime,
		Long      owner
	) {
		this.id = id;
		this.duration = duration;
		this.name = name;
		this.showFullTestsDuringContest = showFullTestsDuringContest;
		this.startTime = startTime;
		this.owner = owner;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Contest setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "duration", precision = 64)
	@Override
	public Duration getDuration() {
		return this.duration;
	}

	@Override
	public Contest setDuration(Duration duration) {
		this.duration = duration;
		return this;
	}

	@Column(name = "name", unique = true, length = 255)
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public Contest setName(String name) {
		this.name = name;
		return this;
	}

	@Column(name = "show_full_tests_during_contest", nullable = false)
	@Override
	public Boolean getShowFullTestsDuringContest() {
		return this.showFullTestsDuringContest;
	}

	@Override
	public Contest setShowFullTestsDuringContest(Boolean showFullTestsDuringContest) {
		this.showFullTestsDuringContest = showFullTestsDuringContest;
		return this;
	}

	@Column(name = "start_time")
	@Override
	public Timestamp getStartTime() {
		return this.startTime;
	}

	@Override
	public Contest setStartTime(Timestamp startTime) {
		this.startTime = startTime;
		return this;
	}

	@Column(name = "owner", precision = 64)
	@Override
	public Long getOwner() {
		return this.owner;
	}

	@Override
	public Contest setOwner(Long owner) {
		this.owner = owner;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IContest from) {
		setId(from.getId());
		setDuration(from.getDuration());
		setName(from.getName());
		setShowFullTestsDuringContest(from.getShowFullTestsDuringContest());
		setStartTime(from.getStartTime());
		setOwner(from.getOwner());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IContest> E into(E into) {
		into.from(this);
		return into;
	}
}
