/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables.pojos;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.ng200.openolympus.jooq.tables.interfaces.IGroupUsers;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
						"http://www.jooq.org",
						"jOOQ version:3.6.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
					"all",
					"unchecked",
					"rawtypes"
})
@Entity
@Table(name = "group_users", schema = "public", uniqueConstraints = {
																		@UniqueConstraint(columnNames = {
																											"group_id",
																											"USER_id"
		})
})
public class GroupUsers implements IGroupUsers {

	private static final long serialVersionUID = 102897412;

	private Long groupId;
	private Long userId;
	private Boolean canAddOthersToGroup;

	public GroupUsers() {
	}

	public GroupUsers(GroupUsers value) {
		this.groupId = value.groupId;
		this.userId = value.userId;
		this.canAddOthersToGroup = value.canAddOthersToGroup;
	}

	public GroupUsers(
			Long groupId,
			Long userId,
			Boolean canAddOthersToGroup) {
		this.groupId = groupId;
		this.userId = userId;
		this.canAddOthersToGroup = canAddOthersToGroup;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IGroupUsers from) {
		this.setGroupId(from.getGroupId());
		this.setUserId(from.getUserId());
		this.setCanAddOthersToGroup(from.getCanAddOthersToGroup());
	}

	@Column(name = "can_add_others_to_group", nullable = false)
	@Override
	public Boolean getCanAddOthersToGroup() {
		return this.canAddOthersToGroup;
	}

	@Column(name = "group_id", nullable = false, precision = 64)
	@Override
	public Long getGroupId() {
		return this.groupId;
	}

	@Column(name = "USER_id", nullable = false, precision = 64)
	@Override
	public Long getUserId() {
		return this.userId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IGroupUsers> E into(E into) {
		into.from(this);
		return into;
	}

	@Override
	public GroupUsers setCanAddOthersToGroup(Boolean canAddOthersToGroup) {
		this.canAddOthersToGroup = canAddOthersToGroup;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	@Override
	public GroupUsers setGroupId(Long groupId) {
		this.groupId = groupId;
		return this;
	}

	@Override
	public GroupUsers setUserId(Long userId) {
		this.userId = userId;
		return this;
	}
}
