/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ng200.openolympus.jooq.Keys;
import org.ng200.openolympus.jooq.Public;
import org.ng200.openolympus.jooq.tables.records.GroupUsersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupUsers extends TableImpl<GroupUsersRecord> {

	private static final long serialVersionUID = 50140981;

	/**
	 * The reference instance of <code>public.group_users</code>
	 */
	public static final GroupUsers GROUP_USERS = new GroupUsers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<GroupUsersRecord> getRecordType() {
		return GroupUsersRecord.class;
	}

	/**
	 * The column <code>public.group_users.group_id</code>.
	 */
	public final TableField<GroupUsersRecord, Long> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.group_users.USER_id</code>.
	 */
	public final TableField<GroupUsersRecord, Long> USER_ID = createField("USER_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.group_users.can_add_others_to_group</code>.
	 */
	public final TableField<GroupUsersRecord, Boolean> CAN_ADD_OTHERS_TO_GROUP = createField("can_add_others_to_group", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.group_users</code> table reference
	 */
	public GroupUsers() {
		this("group_users", null);
	}

	/**
	 * Create an aliased <code>public.group_users</code> table reference
	 */
	public GroupUsers(String alias) {
		this(alias, GROUP_USERS);
	}

	private GroupUsers(String alias, Table<GroupUsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private GroupUsers(String alias, Table<GroupUsersRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<GroupUsersRecord> getPrimaryKey() {
		return Keys.GROUP_USERS_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<GroupUsersRecord>> getKeys() {
		return Arrays.<UniqueKey<GroupUsersRecord>>asList(Keys.GROUP_USERS_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<GroupUsersRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<GroupUsersRecord, ?>>asList(Keys.GROUP_USERS__GROUP_FK, Keys.GROUP_USERS__USER_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupUsers as(String alias) {
		return new GroupUsers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public GroupUsers rename(String name) {
		return new GroupUsers(name, null);
	}
}
