/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ng200.openolympus.jooq.Keys;
import org.ng200.openolympus.jooq.Public;
import org.ng200.openolympus.jooq.tables.records.PropertyRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
						"http://www.jooq.org",
						"jOOQ version:3.6.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
					"all",
					"unchecked",
					"rawtypes"
})
public class Property extends TableImpl<PropertyRecord> {

	private static final long serialVersionUID = -1129036901;

	/**
	 * The reference instance of <code>public.property</code>
	 */
	public static final Property PROPERTY = new Property();

	/**
	 * The column <code>public.property.id</code>.
	 */
	public final TableField<PropertyRecord, Long> ID = AbstractTable
			.createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false),
					this, "");

	/**
	 * The column <code>public.property.property_key</code>.
	 */
	public final TableField<PropertyRecord, String> PROPERTY_KEY = AbstractTable
			.createField("property_key",
					org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.property.property_value</code>.
	 */
	public final TableField<PropertyRecord, byte[]> PROPERTY_VALUE = AbstractTable
			.createField("property_value", org.jooq.impl.SQLDataType.BLOB, this,
					"");

	/**
	 * Create a <code>public.property</code> table reference
	 */
	public Property() {
		this("property", null);
	}

	/**
	 * Create an aliased <code>public.property</code> table reference
	 */
	public Property(String alias) {
		this(alias, Property.PROPERTY);
	}

	private Property(String alias, Table<PropertyRecord> aliased) {
		this(alias, aliased, null);
	}

	private Property(String alias, Table<PropertyRecord> aliased,
			Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Property as(String alias) {
		return new Property(alias, this);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PropertyRecord>> getKeys() {
		return Arrays.<UniqueKey<PropertyRecord>> asList(Keys.PROPERTY_PKEY,
				Keys.UK_8JYTV8TU3PUI7RAM00B44TN4U,
				Keys.UK_4B6VATGJ30955XSJR51YEGXI9);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PropertyRecord> getPrimaryKey() {
		return Keys.PROPERTY_PKEY;
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PropertyRecord> getRecordType() {
		return PropertyRecord.class;
	}

	/**
	 * Rename this table
	 */
	public Property rename(String name) {
		return new Property(name, null);
	}
}
