/**
 * The MIT License
 * Copyright (c) 2014-2015 Nick Guletskii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/**
 * This class is generated by jOOQ
 */
package org.ng200.openolympus.jooq.tables;

import java.time.Duration;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.ng200.openolympus.jooq.Keys;
import org.ng200.openolympus.jooq.Public;
import org.ng200.openolympus.jooq.tables.records.TimeExtensionRecord;
import org.ng200.openolympus.util.DurationConverter;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
						"http://www.jooq.org",
						"jOOQ version:3.6.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
					"all",
					"unchecked",
					"rawtypes"
})
public class TimeExtension extends TableImpl<TimeExtensionRecord> {

	private static final long serialVersionUID = 416558268;

	/**
	 * The reference instance of <code>public.time_extension</code>
	 */
	public static final TimeExtension TIME_EXTENSION = new TimeExtension();

	/**
	 * The column <code>public.time_extension.id</code>.
	 */
	public final TableField<TimeExtensionRecord, Long> ID = AbstractTable
			.createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false)
					.defaulted(true), this, "");

	/**
	 * The column <code>public.time_extension.duration</code>.
	 */
	public final TableField<TimeExtensionRecord, Duration> DURATION = AbstractTable
			.createField("duration", org.jooq.impl.SQLDataType.BIGINT, this, "",
					new DurationConverter());

	/**
	 * The column <code>public.time_extension.reason</code>.
	 */
	public final TableField<TimeExtensionRecord, String> REASON = AbstractTable
			.createField("reason", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.time_extension.user_id</code>.
	 */
	public final TableField<TimeExtensionRecord, Long> USER_ID = AbstractTable
			.createField("user_id",
					org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.time_extension.contest_id</code>.
	 */
	public final TableField<TimeExtensionRecord, Integer> CONTEST_ID = AbstractTable
			.createField("contest_id",
					org.jooq.impl.SQLDataType.INTEGER.nullable(false), this,
					"");

	/**
	 * Create a <code>public.time_extension</code> table reference
	 */
	public TimeExtension() {
		this("time_extension", null);
	}

	/**
	 * Create an aliased <code>public.time_extension</code> table reference
	 */
	public TimeExtension(String alias) {
		this(alias, TimeExtension.TIME_EXTENSION);
	}

	private TimeExtension(String alias, Table<TimeExtensionRecord> aliased) {
		this(alias, aliased, null);
	}

	private TimeExtension(String alias, Table<TimeExtensionRecord> aliased,
			Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeExtension as(String alias) {
		return new TimeExtension(alias, this);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TimeExtensionRecord, Long> getIdentity() {
		return Keys.IDENTITY_TIME_EXTENSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TimeExtensionRecord>> getKeys() {
		return Arrays.<UniqueKey<TimeExtensionRecord>> asList(
				Keys.TIME_EXTENSION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TimeExtensionRecord> getPrimaryKey() {
		return Keys.TIME_EXTENSION_PKEY;
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TimeExtensionRecord> getRecordType() {
		return TimeExtensionRecord.class;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TimeExtensionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TimeExtensionRecord, ?>> asList(
				Keys.TIME_EXTENSION__USER_FK, Keys.TIME_EXTENSION__CONTEST_FK);
	}

	/**
	 * Rename this table
	 */
	public TimeExtension rename(String name) {
		return new TimeExtension(name, null);
	}
}
